spring.application.name=betclick

spring.datasource.url=jdbc:postgresql://localhost:5432/betclick
spring.datasource.username=betclick_user
spring.datasource.password=betclick_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=Zm9vQmFyQmF6UXV4UXV1eU15U2VjcmV0S2V5Rm9yQmV0Q2xpY2tBcHBsaWNhdGlvbjIwMjQ=
jwt.expiration=86400000
